version: '2'

services:
  app:
    image: 'vinay0294/carpet-rest-apis.jar:latest'
    ports:
      - 9090:9090
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/carpet
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mypass@123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:9.6'
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=carpet
      - POSTGRES_HOST_AUTH_METHOD=trust